name: Fetch Upstream

# add github actions permission
permissions:
  actions: write
  contents: write

on:
  schedule:
    - cron: "33 9 */5 * *" # every 3 days
  workflow_dispatch:
  push:
    branches: 
      - drv_only
    paths-ignore:
      # Case-sensitive paths to ignore on push events
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'MergeDbg.cmd'
      - 'TestCI.cmd'
      - '.github/codeql/codeql-config.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/hash.yml'
      - '.github/workflows/lupdate.yml'
      - '.github/workflows/stale.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/winget.yml'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'
      - 'Sandboxie/msgs/report/*.txt'
      - '**/*.md'
      - '**/*.html'
      - '**/*.png'
      - '**/*.bmp'
      - '**/LICENSE*'
      - '**/license*'
      - '**/README*'
      - '**/ReadMe*'
      - '**/INSTALL*'
      - '**/AUTHORS'
      - '**/COPYING'
      - '.github/workflows/drv.yml'
      - '.github/workflows/fetch-upstream.yml'
jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: fetch upstream
        run: |
          git remote add upstream https://github.com/sandboxie-plus/Sandboxie
          git fetch --all
          git switch drv_only
      - name: patch workflow
        run: |
          mv .github/workflows/drv.yml ../
          mv .github/workflows/fetch-upstream.yml ../
          git reset --hard upstream/master
          mv ../drv.yml .github/workflows/
          mv ../fetch-upstream.yml .github/workflows/
      - name: create commit
        run: |
          git config --global user.name 'Yoroizuka Nozomi'
          git config --global user.email '142671432+habatake@users.noreply.github.com'
          git add .
          git commit -m "fetch upstream && add workflows"
          git push -f